//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Account
{
    public Account()
    {
        this.Articles = new HashSet<Article>();
        this.ArticleCategories = new HashSet<ArticleCategory>();
        this.ArticleMainCategories = new HashSet<ArticleMainCategory>();
        this.Contacts = new HashSet<Contact>();
        this.ContactCategories = new HashSet<ContactCategory>();
        this.IntroduceCategories = new HashSet<IntroduceCategory>();
        this.Introduces = new HashSet<Introduce>();
        this.Pictures = new HashSet<Picture>();
        this.PictureCategories = new HashSet<PictureCategory>();
        this.PictureMainCategories = new HashSet<PictureMainCategory>();
        this.Products = new HashSet<Product>();
        this.ProductCategories = new HashSet<ProductCategory>();
        this.ProductInfoes = new HashSet<ProductInfo>();
        this.ProductMainCategories = new HashSet<ProductMainCategory>();
    }

    public string Username { get; set; }
    public string Password { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public string FullName { get; set; }
    public string Email { get; set; }
    public string Mobile { get; set; }
    public Nullable<bool> Gender { get; set; }
    public Nullable<bool> Status { get; set; }
    public string Address { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string AccountCategoryID { get; set; }

    public virtual AccountCategory AccountCategory { get; set; }
    public virtual ICollection<Article> Articles { get; set; }
    public virtual ICollection<ArticleCategory> ArticleCategories { get; set; }
    public virtual ICollection<ArticleMainCategory> ArticleMainCategories { get; set; }
    public virtual ICollection<Contact> Contacts { get; set; }
    public virtual ICollection<ContactCategory> ContactCategories { get; set; }
    public virtual ICollection<IntroduceCategory> IntroduceCategories { get; set; }
    public virtual ICollection<Introduce> Introduces { get; set; }
    public virtual ICollection<Picture> Pictures { get; set; }
    public virtual ICollection<PictureCategory> PictureCategories { get; set; }
    public virtual ICollection<PictureMainCategory> PictureMainCategories { get; set; }
    public virtual ICollection<Product> Products { get; set; }
    public virtual ICollection<ProductCategory> ProductCategories { get; set; }
    public virtual ICollection<ProductInfo> ProductInfoes { get; set; }
    public virtual ICollection<ProductMainCategory> ProductMainCategories { get; set; }
}

public partial class AccountCategory
{
    public AccountCategory()
    {
        this.Accounts = new HashSet<Account>();
    }

    public string AccountCategoryID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }

    public virtual ICollection<Account> Accounts { get; set; }
}

public partial class Article
{
    public int ArticleID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public string Content { get; set; }
    public string Keyword { get; set; }
    public string ImageList { get; set; }
    public string SourcePage { get; set; }
    public string SourceLinhk { get; set; }
    public string AttachmentFile { get; set; }
    public Nullable<int> ViewTime { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> ArticleCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ArticleCategory ArticleCategory { get; set; }
}

public partial class ArticleCategory
{
    public ArticleCategory()
    {
        this.Articles = new HashSet<Article>();
    }

    public int ArticleCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Desition { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> ArticleMainCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Article> Articles { get; set; }
    public virtual ArticleMainCategory ArticleMainCategory { get; set; }
}

public partial class ArticleMainCategory
{
    public ArticleMainCategory()
    {
        this.ArticleCategories = new HashSet<ArticleCategory>();
    }

    public int ArticleMainCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Desition { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<ArticleCategory> ArticleCategories { get; set; }
}

public partial class Contact
{
    public int ContactID { get; set; }
    public string Code { get; set; }
    public string FullName { get; set; }
    public string Email { get; set; }
    public string Address { get; set; }
    public string Mobile { get; set; }
    public string AttachmentFile { get; set; }
    public string Content { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> ContactCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ContactCategory ContactCategory { get; set; }
}

public partial class ContactCategory
{
    public ContactCategory()
    {
        this.Contacts = new HashSet<Contact>();
    }

    public int ContactCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Contact> Contacts { get; set; }
}

public partial class Introduce
{
    public int IntroduceID { get; set; }
    public string Avatar { get; set; }
    public string Title { get; set; }
    public string YearHistory { get; set; }
    public string Description { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public Nullable<int> IntroduceCategoryID { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual IntroduceCategory IntroduceCategory { get; set; }
}

public partial class IntroduceCategory
{
    public IntroduceCategory()
    {
        this.Introduces = new HashSet<Introduce>();
    }

    public int IntroduceCategoryID { get; set; }
    public string Title { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Introduce> Introduces { get; set; }
}

public partial class Order
{
    public Order()
    {
        this.OrderDetails = new HashSet<OrderDetail>();
    }

    public int OrderID { get; set; }
    public string Code { get; set; }
    public Nullable<double> Total { get; set; }
    public string FullName { get; set; }
    public string Mobile { get; set; }
    public string Email { get; set; }
    public string Address { get; set; }
    public Nullable<bool> Gender { get; set; }
    public string Comment { get; set; }
    public Nullable<int> PaymentMethod { get; set; }
    public Nullable<double> Amount { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public Nullable<bool> OrderStatus { get; set; }
    public Nullable<bool> ConfirmStatus { get; set; }
    public Nullable<bool> ChargeStatus { get; set; }
    public Nullable<bool> DeliveStatus { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; }
}

public partial class OrderDetail
{
    public int OrderID { get; set; }
    public int ProductID { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<double> Price { get; set; }

    public virtual Order Order { get; set; }
    public virtual Product Product { get; set; }
}

public partial class Picture
{
    public int PictureID { get; set; }
    public string Code { get; set; }
    public string Avatar { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Thumb { get; set; }
    public string Url { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> PictureCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual PictureCategory PictureCategory { get; set; }
}

public partial class PictureCategory
{
    public PictureCategory()
    {
        this.Pictures = new HashSet<Picture>();
    }

    public int PictureCategoryID { get; set; }
    public string COde { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> PictureMainCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Picture> Pictures { get; set; }
    public virtual PictureMainCategory PictureMainCategory { get; set; }
}

public partial class PictureMainCategory
{
    public PictureMainCategory()
    {
        this.PictureCategories = new HashSet<PictureCategory>();
    }

    public int PictureMainCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<PictureCategory> PictureCategories { get; set; }
}

public partial class Product
{
    public Product()
    {
        this.OrderDetails = new HashSet<OrderDetail>();
        this.ProductInfoes = new HashSet<ProductInfo>();
    }

    public int ProductID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Thumb { get; set; }
    public string Avatar { get; set; }
    public string Content { get; set; }
    public Nullable<double> Price { get; set; }
    public Nullable<double> OldPrice { get; set; }
    public string Keyword { get; set; }
    public string ImageList { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public Nullable<int> Position { get; set; }
    public string Taste { get; set; }
    public string Name { get; set; }
    public string AddressProduct { get; set; }
    public string BgAvatar1 { get; set; }
    public string BgAvatar2 { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> ProductCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    public virtual ProductCategory ProductCategory { get; set; }
    public virtual ICollection<ProductInfo> ProductInfoes { get; set; }
}

public partial class ProductCategory
{
    public ProductCategory()
    {
        this.Products = new HashSet<Product>();
    }

    public int ProductCategoryID { get; set; }
    public string Code { get; set; }
    public string Description { get; set; }
    public string Thumb { get; set; }
    public string Avatar { get; set; }
    public string Title { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> ProductMainCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Product> Products { get; set; }
    public virtual ProductMainCategory ProductMainCategory { get; set; }
}

public partial class ProductInfo
{
    public int ProductInfoID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> ProductID { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> Position { get; set; }

    public virtual Account Account { get; set; }
    public virtual Product Product { get; set; }
}

public partial class ProductMainCategory
{
    public ProductMainCategory()
    {
        this.ProductCategories = new HashSet<ProductCategory>();
    }

    public int ProductMainCategoryID { get; set; }
    public string Code { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Title { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<ProductCategory> ProductCategories { get; set; }
}
